FROM ubuntu:focal
LABEL maintainer="Andrew Beltrano <anbeltra@microsoft.com>"
ENV DEBIAN_FRONTEND=noninteractive

RUN echo "deb-src http://archive.ubuntu.com/ubuntu focal main" >> /etc/apt/sources.list.d/kernel-src.list && \
    echo "deb-src http://archive.ubuntu.com/ubuntu focal-updates main" >> /etc/apt/sources.list.d/kernel-src.list
RUN apt update 
RUN apt-get -y build-dep linux 
RUN apt install -y git wireless-tools vim

# Download wsl2 kernel source.
WORKDIR /usr/src/linux/
RUN git clone --depth 1 --branch linux-msft-wsl-$(uname -r | cut -d - -f 1) https://github.com/microsoft/WSL2-Linux-Kernel.git wsl2
WORKDIR /usr/src/linux/wsl2

# Copy kernel build config
RUN cp Microsoft/config-wsl .config

# Compile hwsim and deps as modules
RUN echo "CONFIG_WLAN=y" >> .config && \
  echo "CONFIG_CFG80211=m" >> .config && \
  echo "CONFIG_MAC80211=m" >> .config && \
  echo "CONFIG_MAC80211_HWSIM=m" >> .config

# Silently add required defaults & prepare to compile mods
RUN make olddefconfig
RUN make modules_prepare

# Compile the modules
RUN make M=net/wireless
RUN make M=net/mac80211
RUN make M=drivers/net/wireless

# Copy them to where we'll need them
# RUN mkdir /kmod/ \
#   && cp /usr/src/linux/drivers/net/wireless/mac80211_hwsim.ko \
#   /usr/src/linux/net/wireless/cfg80211.ko \
#   /usr/src/linux/net/mac80211/mac80211.ko /kmod/

# Install ztp dev dependencies
RUN apt install -y \
    build-essential \
    cmake \
    git \
    libboost-filesystem-dev \
    libboost-random-dev \
    libboost-regex-dev \
    libboost-system-dev \
    libboost-thread-dev \
    libbrotli-dev \
    libgpiod-dev \
    libjson-c-dev \
    libssl-dev \
    libsystemd-dev \
    pkg-config \
    zlib1g-dev