
#ifndef __ZTP_VERSION_H__
#define __ZTP_VERSION_H__

// Current version information.
#define ZTP_VERSION_MAJOR ZTPCORE_VERSION_MAJOR
#define ZTP_VERSION_MINOR ZTPCORE_VERSION_MINOR
#define ZTP_VERSION_PATCH ZTPCORE_VERSION_PATCH
#define ZTP_VERSION_TWEAK ZTPCORE_VERSION_TWEAK
#define ZTP_VERSION ZTPCORE_VERSION

#endif // __ZTP_VERSION_H__
